### PR TITLE
OOIION-1797 Splits creating a dataset and activating into two distinct methods

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
@mmeisinger Ready for review

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/231

**Comment by mmeisinger** [comment]
:+1: I'm waiting for the pull builder. There is an issue because not all of the DPMS.catalog_entry operations are implemented (concurrent work). That's OK for a bit until the other work is merged

**Comment by lukecampbell** [comment]
Rebased, after including the stubs, pull should work.

**Comment by lukecampbell** [comment]
rebased.

**Pull request merged**
