### PR TITLE
Mission exec events

### PR DESCRIPTION
**Pull request by Bobfrat**
@edwardhunter, @carueda Please review

-Clean up platform agent methods within mission exec (not needed)
-Add mission events

### CODE REVIEW

**Comment by carueda** [comment]
Edward: I think Bob forgot to mention that this is not ready yet to be merged as the ion-definitions pointer hasn't been updated here. But I suggested him to go ahead with the PR to facilitate my review.

**Comment by edwardhunter** [comment]
OK. I will not merge until later

**Comment by carueda** [comment]
Edward: Do not merge this.  I'm working on another PR, where I have merged Bob's changes, and will be adding some more to that.  Thx.

**Comment by carueda** [comment]
Superseded by #2082

(this PR can be closed.)

**Pull request closed without merging**
