### PR TITLE
Better retrieve support for data management

### PR DESCRIPTION
**Pull request by lukecampbell**
Faster retrieve capabilities using coverage model features, and supports managing of duplicate values.

Part of [OOIION-1310](https://jira.oceanobservatories.org/tasks/browse/OOIION-1310)

### CODE REVIEW

**Comment by lukecampbell** [comment]
[coi_smoke 2903](http://buildbot.oceanobservatories.org:8010/builders/coi_smoke/builds/2903)

**Comment by lukecampbell** [comment]
[DM Test Suite](http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/110)

**Comment by lukecampbell** [comment]
[coi smoke 2910](http://buildbot.oceanobservatories.org:8010/builders/coi_smoke/builds/2910)

**Comment by lukecampbell** [comment]
[DM Test Suite](http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/112)

**Comment by lukecampbell** [comment]
[DM Test Suite](http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/118)

**Comment by lukecampbell** [comment]
@jamie-cyber1 Tests Pass (finally) Ready to merge!

**Comment by jamie-cyber1** [comment]
:+1:

**Pull request merged**
