### PR TITLE
fixes problem in service gateway with handling dicts; bumps pyon to include unicode to utf8 str encoding

### PR DESCRIPTION
**Pull request by pkediyal**
pyon pull request needs to be merged before this pull request

### CODE REVIEW

**Comment by pkediyal** [comment]
As long as my pyon pull request goes in before this one we should be good.

**Comment by shenrie** [comment]
Looks like there is a problem with merging this PR, can you see what needs to be fixed for a successful merge?

**Comment by pkediyal** [comment]
probably just need to bump pyon do you want me to do that?

**Comment by pkediyal** [comment]
let me check anyway

**Comment by shenrie** [comment]
Please

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by pkediyal** [comment]
hey did you try to merge or rebase?

**Comment by shenrie** [comment]
No.. I just tried  to use the  web interface.  Your changes are so minimal for this PR, it would be easier for me to just replicate them and push myself

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Pull request closed without merging**
