### PR TITLE
CIDEVSTC-279 - M088 Human in the loop QC Data Upload

### PR DESCRIPTION
**Pull request by brianmckenna**
adds integration test and example NetCDF file for test

@MauriceManning @lukecampbell

### CODE REVIEW

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/238

**Comment by lukecampbell** [comment]
:+1: I'll merge when the test is done and @MauriceManning glances it over

**Comment by MauriceManning** [comment]
:+1:  merge when ready

**Comment by lukecampbell** [comment]
Boom done.

**Pull request merged**
