### PR TITLE
Lots of code cleanup for data products

### PR DESCRIPTION
**Pull request by lukecampbell**
Let the code cleanup begin!

depends on ion-defs https://github.com/ooici/ion-definitions/pull/567

### CODE REVIEW

**Comment by lukecampbell** [comment]
@MauriceManning @mmeisinger

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/250

**Comment by mmeisinger** [comment]
Looks good to me. Wow this spat/temp domain stuff was pervasive.

**Comment by lukecampbell** [comment]
Submodule bumped, coi_smoke should pass now. Please note that the tests passed for all 
nose 116 tests 3306.891s SKIPS=37 

affected modules.

**Pull request merged**
