### PR TITLE
OOIION-1770: Add set_calibration option to agentctrl script

### PR DESCRIPTION
**Pull request by mmeisinger**
first part of implementation

### CODE REVIEW

**Comment by mmeisinger** [comment]
@lukecampbell please continue
@jamie-cyber1 please review

**Comment by lukecampbell** [comment]
I thought this was for R2.2

**Comment by jamie-cyber1** [comment]
Needs for both.

**Comment by lukecampbell** [comment]
I have a PR on his branch that includes the changes requested
https://github.com/mmeisinger/coi-services/pull/2

Once Michael makes an R2 branch, I'll cherry-pick those changes over into that branch as well.

**Comment by mmeisinger** [comment]
PR was updated (rebased, squashed and force pushed).
@jamie-cyber1 please merge

**Comment by jamie-cyber1** [comment]
The build failed.

**Pull request merged**
