### PR TITLE
OOIION-1660 Adds re-registration process

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
Standby, I'm going to rebase this branch since it's quite old.

**Comment by lukecampbell** [comment]
@MauriceManning These will be ready to merge as soon as the test finishes.

**Comment by lukecampbell** [comment]
@MauriceManning Ready to merge

**Comment by MauriceManning** [comment]
:thumbsup:

**Pull request merged**
