### PR TITLE
Adds test_cabled_deployments

### PR DESCRIPTION
**Pull request by lukecampbell**
This test suite is the core set of tests that verifies the functionality delivered in M193

### CODE REVIEW

**Comment by lukecampbell** [comment]
Copied from email:

```
hi Luke
Looks fine, a couple notes:
- it doesnt look like the instrument model gets assigned to the instrument device, assign_instrument_model_to_instrument_device
- you can use assign_instrument_device_to_platform_device_with_has_device to connect devices
- your sites to not have models assigned ( assign_instrument_model_to_instrument_site ) which is checked in deployment_activator:_validate_models
- Carlos has nice examples of setting up various structures here:
https://github.com/ooici/coi-services/blob/master/ion/agents/platform/test/base_test_platform_agent_with_rsn.py

Im not sure how much you want to do with the test but for deployments, the above would be good.
```

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/268

**Comment by lukecampbell** [comment]
@mmeisinger @MauriceManning 
(SA Tests) http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/269

This should be a good starting point and once I get the second deployment in here, it will be a complete example of M193.

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/271

**Comment by lukecampbell** [comment]
@mmeisinger @MauriceManning So this sums up the core of M193.

I'll be adding follow up variations of this to test:
- Multiple deployments
- Complicated trees of platform/devices
- parameter mismatching
- (Later in transition if there's time) error handling and edge-case

**Comment by lukecampbell** [comment]
Ready to merge

**Comment by MauriceManning** [comment]
:+1:  Nice test...

**Pull request merged**
