### PR TITLE
Luke: association deletion

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by dstuebe** [comment]
Hmmm - I don't think this is quiet right yet.
For instance with the index - the delete index function should not delete the associations from a catalog created by catalog mgmt service. It is the responsibility of the user to delete the catalogs association (or the entire catalog) before deleting the index. That pattern should be implemented in the tests as well so that associations are not left behind and the correct service which is responsible for the association is deleting it.

**Comment by dstuebe** [comment]
This looks better. Lets see if all the warnings go away.

**Comment by lukecampbell** [comment]
Where are the warnings?

**Comment by dstuebe** [comment]
Here is what to look for:
https://github.com/ooici/pyon/blob/master/pyon/datastore/couchdb/couchdb_datastore.py#L308

David

On Thu, Jun 14, 2012 at 11:36 AM, Luke Campbell <
reply@reply.github.com

**Pull request merged**
