### PR TITLE
M101 - abort mission functionality

### PR DESCRIPTION
**Pull request by Bobfrat**
@edwardhunter, @carueda please review...
Added the following methods:
-abort_mission
-instrument_abort_sequence

modified yaml mission file -instrument to -missionThread

### CODE REVIEW

**Comment by carueda** [comment]
Looks good.  All relevant tests passing?

**Comment by Bobfrat** [comment]
Passed on my machine.

**Comment by carueda** [comment]
OK, so good to be merged IMO.  (despite the failures on buildbot as they seem caused by other changes.)  Edward?

**Comment by Bobfrat** [comment]
@edwardhunter is this ok to merge?

**Pull request merged**
