### PR TITLE
OOIION-1756 Terminate high availability agent thread safely

### PR DESCRIPTION
**Pull request by jamie-cyber1**

### CODE REVIEW

**Comment by jamie-cyber1** [comment]
@daf please review and merge.

**Comment by daf** [comment]
Seems fine.  Could probably somehow combine these two event loops but this is a definite better approach than what we had.  Will merge when build passes.

**Comment by jamie-cyber1** [comment]
Okay I will look into combining it.

**Comment by daf** [comment]
Looking at it quickly I'm not sure there's a simple approach as they really are serving different purposes.  Maybe hold off for another PR?

**Comment by jamie-cyber1** [comment]
Okay. Then go ahead and merge then.

**Pull request merged**
