### PR TITLE
update module pointer for ion-definitions

### PR DESCRIPTION
**Pull request by birdage**
updates module pointer for ion-definitions since update

### CODE REVIEW

**Comment by birdage** [comment]
@jamie-cyber1 pointer update

**Comment by jamie-cyber1** [comment]
:+1:

**Comment by jamie-cyber1** [comment]
@MauriceManning and @lukecampbell please take a look at unit test and smoke test failures.
@mmeisinger uns unit test failure is probably yours?

**Comment by birdage** [comment]
@mmeisinger uns?, the bug report does not look related to this i dont think.

**Comment by lukecampbell** [comment]
https://github.com/ooici/coi-services/pull/1965

**Pull request closed without merging**
