### PR TITLE
calculate portal status even when not part of master status dict

### PR DESCRIPTION
**Pull request by newbrough**
prior implementation was extracting status of portal devices from main list of device statuses, but several cases had portal devices that were not in the device list of the site/facility.

### CODE REVIEW

**Comment by mmeisinger** [comment]
Careful. This PR seems to have had much more impact than anticipated. Please check that this one did not revert other people's changes

**Comment by daf** [comment]
`git-rebase master` yw

**Comment by blazetopher** [comment]
It seems to have re-committed a number of recent commits (recent ones from me are in there for example)

Jonathan - it looks like you may have merged the most recent master and then created and merged the PR?  This effectively re-commits all the commits you merge into master locally.  Rebase is a better approach (as Dave just commented)...

**Comment by blazetopher** [comment]
Didn't notice the direction of the PR - I get it now...sort of :/

**Pull request merged**
