### PR TITLE
Adds complex coverage stubs and Code Cleanup

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
Depends on https://github.com/ooici/ion-definitions/pull/582

**Comment by lukecampbell** [comment]
@jamie-cyber1 @MauriceManning @mmeisinger Please review and merge at your leisure

**Comment by mmeisinger** [comment]
:+1: It all looks very good and straightforward. Saw no issues. Long needed clean-up. Thanks for taking the time to remove unnecessary code and tests.

**Comment by lukecampbell** [comment]
Am I going to be the @$$hole that breaks buildbot over the weekend you ask? Why yes, yes I am... probably.

**Pull request merged**
