### PR TITLE
CIDEVSTC-288 - QC Processing

### PR DESCRIPTION
**Pull request by lukecampbell**
The first iteration of the QC Processor. 
- Doesn't store data until the CM is ready but it gets the data as close as possible to ready
- Still needs to apply windows and RD lookups for multi-deployment

It actually works!

### CODE REVIEW

**Comment by lukecampbell** [comment]
@MauriceManning ready for your review.
There's no tests and it's no where near ready for integration (because of M088's dependencies) but worst-comes-to-worst it runs and we can integrate it easily if it becomes imperative.

**Comment by lukecampbell** [comment]
I'm gonna put back in the prelaod stuff, I think it's premature to make that jump.

**Comment by lukecampbell** [comment]
There, now we can safely merge it.

**Comment by MauriceManning** [comment]
:+1:  good start.

**Pull request merged**
