### PR TITLE
M101 - Mission manager tests

### PR DESCRIPTION
**Pull request by Bobfrat**
Added the following tests to test_mission_manager:
- test_mission_abort (intentional failed mission file)
- test_mission_multiple_instruments (mission file with multiple mission
  threads
- test_simple_event_driven_mission (event driven mission example)

@carueda, @edwardhunter, please review

### CODE REVIEW

**Comment by Bobfrat** [comment]
BTW these tests take a couple minutes each to run.

**Comment by lukecampbell** [comment]
Could you throw these on coi_any?
http://buildbot.oceanobservatories.org:8010/builders/coi_any/

**Comment by carueda** [comment]
@edwardhunter what do you think? I don't have any particular opinion here aside from following whatever is needed for appropriate testing of the platform agent and mission executive on buildbot.

**Comment by carueda** [comment]
I cannot test this on my machine because of connection issues (which Baha is helping me diagnose).

But Bob reports that the tests are completing fine for him, so @edwardhunter please merge.

**Pull request merged**
