### PR TITLE
OOIION-1797 Splits creating a dataset and activating into two distinct methods R2

### PR DESCRIPTION
**Pull request by lukecampbell**
DON'T MERGE: DEPENDS ON SUBMODULE CHANGE https://github.com/ooici/ion-definitions/pull/534/files

### CODE REVIEW

**Comment by lukecampbell** [comment]
@mmeisinger Ready for review, don't merge until submodule changes are in, thanks.

**Comment by lukecampbell** [comment]
Ready to merge after review, submodule is updated.

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/230

**Comment by mmeisinger** [comment]
Nice.

Is create_dataset_for_data_product idempotent? Does it catch whether it was called already for a data product and the coverage already exists? Should it?

**Comment by mmeisinger** [comment]
:+1: By looking at the code I found out yes to my question. Very nice. Thanks for the quick refactor!

**Pull request merged**
