### PR TITLE
M101 - Mission executive

### PR DESCRIPTION
**Pull request by Bobfrat**
-Adds publishing of MissionLoader events

@carueda please review and if OK @edwardhunter can merge

### CODE REVIEW

**Comment by carueda** [comment]
Bob: It seems you didn't update a relevant unit test. Please update the PR with the fix so it can be merged.  Otherwise looks good.  (although we may need to change the handling of potential error with the given mission file as mentioned in email.)

**Comment by Bobfrat** [comment]
@carueda @edwardhunter - OK unit test passed.

**Comment by carueda** [comment]
Thanks! Good to merge.

**Comment by Bobfrat** [comment]
Just added another commit with more mission executive event publishing.

**Pull request merged**
