### PR TITLE
reverse OOIION-1025 fix by jnewbrough

### PR DESCRIPTION
**Pull request by pkediyal**
Jonathan fixed 1025 for issues that were already addressed by policy. This undoes those changes https://jira.oceanobservatories.org/tasks/browse/OOIION-1025

### CODE REVIEW

**Comment by pkediyal** [comment]
hold on .. don't merge yet

**Comment by mmeisinger** [comment]
I will review and merge when ready.

**Comment by pkediyal** [comment]
basically jonathan added test cases for these changes and they need to be undone as well.

**Comment by pkediyal** [comment]
go ahead merge it now.

**Comment by mmeisinger** [comment]
Looks good

**Pull request merged**
