### PR TITLE
Simple test to use the stubs

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
depends on https://github.com/ooici/ion-definitions/pull/586

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/255

**Comment by lukecampbell** [comment]
@MauriceManning Ready for review and merge at your leisure.

**Comment by MauriceManning** [comment]
:+1:

**Pull request merged**
