### PR TITLE
Updates the preload behavior for streams and how the agent configures streams

### PR DESCRIPTION
**Pull request by lukecampbell**
- Interface update to DPMS' create_data_product
- Preload change to manage stream configurations as a reference in the standard R2 preload spreadsheet
- Preload changes to deal with stream configurations during an OOI preload from SAF
- Agent configuration refactor of the algorithm
- Test fixes

### CODE REVIEW

**Comment by lukecampbell** [comment]
@MauriceManning please review

**Comment by lukecampbell** [comment]
Once this is merged I can move forward with adding parameters and creating individual parameter dictionaries for data products.

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/248

**Comment by mmeisinger** [comment]
Looks good to me on cursory glance

**Pull request merged**
