### PR TITLE
CIDEVSTC-288 - Event handling in the QC Process

### PR DESCRIPTION
**Pull request by lukecampbell**
- Refactors preload a bit to move all the qc handling into a function that's called by load parameter
- Adds an event subscriber to QC Processor to listen for incoming events and then append them to a queue
- At the conclusion of the qc processing loop, each event in the event queue is handled.
  - The events will typically result in QC being re-evaluated for larger sets of data.

### CODE REVIEW

**Comment by lukecampbell** [comment]
@MauriceManning 
@mmeisinger 
Ready for review and discussion

**Comment by mmeisinger** [comment]
Refactoring looks good. The event type is probably not right. Is it really ParameterQCEvent? Do we need to refine the event type hierarchy wrt QC events? There are TONS of ParameterQCEvent in the system.

I don't see high level try-except in your basic thread loops. Make sure these cannot die

**Comment by MauriceManning** [comment]
We might want to create the QCProcess event under DataProcessEvent?

**Comment by lukecampbell** [comment]
The event type doesn't exist yet, I just used QCParameterEvent as a place holder until I iron out all the cases which require events from the requirements. There's a few.

**Comment by lukecampbell** [comment]
Just a point of clarification, this PR doesn't affect the system in any way. I'm just trying to get code merged in while also stimulating understanding about what's happening at this level through discussions in PRs.

**Pull request merged**
