### PR TITLE
implement conversation log

### PR DESCRIPTION
**Pull request by pkediyal**

### CODE REVIEW

**Comment by pkediyal** [comment]
will need to bump pyon as well, once you merge that PR

**Comment by shenrie** [comment]
I am confused. What pyon change needs to be pushed?

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by pkediyal** [comment]
so the conversation log stuff here depends on the conversation log stuff we pushed in pyon which will be available in coi-services when we bump the extern/pyon

**Comment by shenrie** [comment]
Maybe I didn't see the PR for pyon then….

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Comment by shenrie** [comment]
No wait.. That is the one that says can't be merged… https://github.com/ooici/pyon/pull/361

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

From: Stephen Henrie <shenrie@ucsd.edu<mailto:shenrie@ucsd.edu>>
Date: Wed, 15 May 2013 18:59:31 -0700
To: ooici/coi-services <reply@reply.github.com<mailto:reply@reply.github.com>>, ooici/coi-services <coi-services@noreply.github.com<mailto:coi-services@noreply.github.com>>
Subject: Re: [coi-services] implement conversation log (#1083)

Maybe I didn't see the PR for pyon then….

---

Stephen P. Henrie  mailto:shenrie@ucsd.edu
System Architect
Ocean Observatories Initiative Cyberinfrastructure Project: http://ci.oceanobservatories.orghttp://ci.oceanobservatories.org/

**Pull request merged**
