### PR TITLE
CIDEVSTC-99: Directory service enhancements for count and skip

### PR DESCRIPTION
**Pull request by brianmckenna**
M112 - T131 SKIP parameter and total results in DB

M112-T131-A002 Return total results available in DB
M112-T131-A005 Process offset (skip) parameter for pagination
M112-T134-A002 Testing skip/offset parameter, implemented with M112-T131-A005
M112-T134-A002 Testing return count, implemented with M112-T131-A002

### CODE REVIEW

**Comment by brianmckenna** [comment]
@mauricemanning @mmeisinger  ready for review

**Comment by mmeisinger** [comment]
The operations parse and query are part of the YML service interface. You cannot add parameters here.

Please do not change the operation signature. Count is a special case. I would leave it away and do an id_only=True query instead.

**Comment by mmeisinger** [comment]
To be more precise: it's good that you use id_only=True for the datastore query, but you need to indicate the count argument in the existing query arguments.

This means either extending the query DSL or adding a count: True key to the query intermediate format dict.

The rest of the changes looks good.

**Comment by lukecampbell** [comment]
I think that we need to change the method signature to include this. I just evaluated what it would take to put it inside the query dictionary it's far simpler to accept it as an argument in the method.

Example

Our goal is to provide the UI with the count information: so the way I see this happening is that the UI makes two service calls. The first asking for the count of the query it's about to perform. The second is the query (with pagination). 

In the case of simple search (text box) the UI doesn't send a dictionary, which we would require if we didn't extend the method signature. Which has a consequence that we would need to extend the query language to add a new noun and update the parsing etc.  There's nothing wrong with this but I think it's just simpler to update the service method signature in lieu of updating the UI to append "COUNT" to every search string to get the count and updating the query language.

**Comment by mmeisinger** [comment]
please add a search_args dict to the signature, not the count. count is a well known key in this search args dict, but this leaves room for other expansion.

We cannot afford to change the signature every so often

**Comment by brianmckenna** [comment]
working on updating tests to reflect new return, once tests are modified will comment to request review/merge

**Comment by lukecampbell** [comment]
Hold off on merging this PR until we merge https://github.com/ooici/ion-definitions/pull/487 and bump ion-defs.

**Comment by brianmckenna** [comment]
ready for review and merge again. output kept as array, so no UI modifications necessary

**Comment by mmeisinger** [comment]
Please update ion-definitions pointer. The changes are ready to merge afterwards

**Comment by mmeisinger** [comment]
This PR did not contain the latest pointer to ion-definitions. The merge is now broken

**Comment by lukecampbell** [comment]
I fixed it. Typo.

**Pull request merged**
