### PR TITLE
CIDEVSTC-278 - Adds test to verify parameter functions can be added and run

### PR DESCRIPTION
**Pull request by lukecampbell**
- Adds better exception logging for retrieve and CM operations.
- Adds test for data process/data process definition management of
  parameter functions.
  - Fully functioning!
- Promotes test_append_parameter to INT test
- Small tweaks to data processing to get the test to work: add
  association and typo

[CIDEVSTC-278](https://jira.oceanobservatories.org/tasks/browse/CIDEVSTC-278)

### CODE REVIEW

**Comment by lukecampbell** [comment]
@MauriceManning ready for review only.
This PR depends on the coverage model PR and submodule update here: 
https://github.com/ooici/coverage-model/pull/142
https://github.com/ooici/coverage-model/pull/143

**Comment by MauriceManning** [comment]
:+1:

**Comment by lukecampbell** [comment]
@MauriceManning ready for merge

**Comment by lukecampbell** [comment]
Here's the test running on coi_any
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/161

**Pull request merged**
