### PR TITLE
OOIION-1607: Add InformationContentAccessedEvent to visualization

### PR DESCRIPTION
**Pull request by mmeisinger**

### CODE REVIEW

**Comment by mmeisinger** [comment]
@jamie-cyber1 ion-defs need to be merged first

**Comment by mmeisinger** [comment]
waiting for the merge of 1609 before updating this

**Comment by jamie-cyber1** [comment]
Please re-update pull request so it's mergeable.

**Comment by mmeisinger** [comment]
The content of the PR is good. It should be merged in the context of a more general work tracking data access.

**Pull request closed without merging**
