### PR TITLE
fix visualization service policy issue OOIION-1102

### PR DESCRIPTION
**Pull request by pkediyal**

### CODE REVIEW

**Comment by pkediyal** [comment]
Description of changes: The name of the service was recently changed to visualization by Raj, apparently Stephen made changes to the policy to accommodate that but forgot to change it in another place, in addition the name of the operation initiate_realtime_visualization_data was spelled incorrectly as initiate_realtime_visualization. This has now been tested locally and should work.

**Comment by pkediyal** [comment]
code changes are trivial, review and merge with confidence or else assign to jamie and I can do a code review with her. Of course I would merge right now on my own but you had asked that I do code reviews.

**Comment by mmeisinger** [comment]
Should this be merged or reviewed?

**Comment by pkediyal** [comment]
To answer your question: If it were up to me I would merge it. 

In fact I would have already merged it myself now that I have the appropriate permissions on github. But you had asked that I get it reviewed it by you or jamie so I assigned it to you to merge so that you may review before merge. See comments above for a description of the changes and also for the pointer that there is not much to review as the code changes are quite trivial.

**Comment by mmeisinger** [comment]
Looks good. Clearly an oversight not applying name changes to policy

**Pull request merged**
