### PR TITLE
OOIION-1669: Appropriate role in one Org enables  activate (suspend) dat...

### PR DESCRIPTION
**Pull request by pkediyal**
@jamie-cyber1 please review

### CODE REVIEW

**Comment by jamie-cyber1** [comment]
Please fill in pull request info and how you've tested this in jira.

**Comment by pkediyal** [comment]
@jamie-cyber1 information filled

**Comment by pkediyal** [comment]
note: this pull request fixes two bugs 1669, 1673. However each bug has a different commit.

**Comment by jamie-cyber1** [comment]
Please open separate pull requests for each bug.  I will close this one.

**Pull request closed without merging**
