### PR TITLE
M101 Mission executive - update ports on/off command

### PR DESCRIPTION
**Pull request by Bobfrat**
-Update the command to use the execute_resource method within platform
agent
-Clean up mission_executive.py a bit

@carueda, @edwardhunter please review

### CODE REVIEW

**Comment by carueda** [comment]
Looks good.

**Comment by carueda** [comment]
I just merged this locally, ran the test:

```
bin/nosetests -sv  --with-pycc ion/agents/platform/test/test_mission_manager.py:TestPlatformAgentMission.test_simple_mission_ports_on_off
```

and looked at the logs for the turn on/off:

```
ion.agents.mission_executive:737 [mm] LJ01D
ion.agents.mission_executive:744 [mm] Mission command = TURN_ON_PORT, Attempt # 1
ion.agents.mission_executive:642 [mm] Send mission command =  execute_resource - TURN_ON_PORT
ion.agents.platform.rsn.rsn_platform_driver:688 'LJ01D': turning on port: port_id=None instrument_id=SBE37_SIM_02
ion.agents.platform.rsn.rsn_platform_driver:699 'LJ01D': turn_on_platform_port response: {'LJ01D': {'1': 'OK_PORT_TURNED_ON'}}
```

Nice! It seems the functionality is in place now, Good progress!

(but worth noting that this is still using the hard-coded 'SBE37_SIM_02' instrument ID, as we don't yet have resolved the ID issue. )

@edwardhunter please merge.

**Comment by Bobfrat** [comment]
Good point Carlos, I had that hardcoded for my own testing purposes and meant to comment that out before I committed. Should I make another commit with line 657 commented?

**Comment by carueda** [comment]
No, that's fine at this point. That comment was more for Edward.

**Pull request merged**
