### PR TITLE
OOIION-1565 Refactor deployment activation logic

### PR DESCRIPTION
**Pull request by MauriceManning**
fix and add port assignment objects to Deployments

@jamie-cyber1  please review
@mmeisinger  please review

### CODE REVIEW

**Comment by jamie-cyber1** [comment]
The smoke build failed.
Do you need the REL2.0 pull request as well?

**Comment by mmeisinger** [comment]
Is this the full PR or are you missing commits? Did you reenable DPD on purpose?

**Comment by MauriceManning** [comment]
This is the mod to support the changes in the Deployment preload sheet. The other files to address changes to port assignment processing will go into 3.0 as a separate PR when this is merged. I reverted the change so that DPDs are not enabled in the 3.0 version. The 2.0 PR is now available as well.

**Comment by mmeisinger** [comment]
:+1:

**Pull request merged**
