### PR TITLE
Adds Lat/Lon support for stationary instruments (M086)

### PR DESCRIPTION
**Pull request by lukecampbell**

### CODE REVIEW

**Comment by lukecampbell** [comment]
http://buildbot.oceanobservatories.org:8010/builders/coi_any/builds/278

**Comment by lukecampbell** [comment]
@Bobfrat care to merge?

**Comment by mmeisinger** [comment]
:+1: Looks good. Just note that this is a 3x nested for loop with database operations inside. The number of total queries should not get excessive though

**Comment by Bobfrat** [comment]
@lukecampbell  I don't have write access to the repo...

**Pull request merged**
